/* ═══════════════════════════════════════════
   Canada ExpGroup Dashboard — App Logic
   ═══════════════════════════════════════════

   Data Strategy:
   - data.js  → pre-baked dataset (run update-data.js to refresh)
               This file is generated by fetching the Open Canada API
               and joining with MapDeptGroup.xlsx at build time.
   ═══════════════════════════════════════════ */

var dataJson = null;    // Will hold the processed/joined data
var mainChart = null;

// Dynamic State
var selectedMain = null;
var selectedCompare = new Set();
var selectedSlicers = new Set();
var isCombineOn = true;

// Colors for Standard Object (SOBJ / expense type) slicers
var SLICER_COLORS = [
    '#f43f5e',
    '#3b82f6',
    '#f59e0b',
    '#06b6d4',
    '#10b981',
    '#8b5cf6',
    '#ec4899',
    '#a78bfa',
    '#34d399',
    '#fbbf24',
    '#60a5fa',
    '#f97316',
];

// Colors for Compare With lines
var COMPARE_COLORS = [
    '#10b981',
    '#8b5cf6',
    '#ec4899',
    '#f59e0b',
    '#06b6d4',
];

// Sentinel value for unmapped organizations
var EMPTY_MAP_LABEL = '<EMPTY FIELD - MAP>';

// DOM Nodes
var mainDropdownTrigger = document.getElementById('mainDropdownTrigger');
var mainSearch = document.getElementById('mainSearch');
var mainList = document.getElementById('mainList');
var compareDropdownTrigger = document.getElementById('compareDropdownTrigger');
var compareSearch = document.getElementById('compareSearch');
var compareList = document.getElementById('compareList');
var compareClearBtn = document.getElementById('compareClearBtn');
var slicerArea = document.getElementById('slicerArea');
var combineToggle = document.getElementById('combineToggle');
var emptyState = document.getElementById('emptyState');
var chartWrapper = document.querySelector('.chart-wrapper');
var chartTitle = document.getElementById('chartTitle');
var dataStatus = document.getElementById('dataStatus');

// ── Init Theme ──────────────────────────────────────────────────────────────────
var isLightMode = localStorage.getItem('theme') === 'light';

function initTheme() {
    if (isLightMode) {
        document.documentElement.setAttribute('data-theme', 'light');
        document.getElementById('themeIcon').textContent = '🌙';
    }
    
    document.getElementById('themeToggleBtn').addEventListener('click', function() {
        isLightMode = !isLightMode;
        if (isLightMode) {
            document.documentElement.setAttribute('data-theme', 'light');
            document.getElementById('themeIcon').textContent = '🌙';
            localStorage.setItem('theme', 'light');
        } else {
            document.documentElement.removeAttribute('data-theme');
            document.getElementById('themeIcon').textContent = '☀️';
            localStorage.setItem('theme', 'dark');
        }
        if (mainChart) updateChart();
    });
}

// ── Init ──────────────────────────────────────────────────────────────────────
function init() {
    try {
        initTheme();
        // Load pre-baked data (generated by running update-data.js)
        if (typeof DASHBOARD_DATA === 'undefined') {
            throw new Error('data.js not found. Please run update-data.js first (or double-click update.bat).');
        }

        dataJson = DASHBOARD_DATA;

        // Initialize all slicers as selected
        dataJson.slicerCats.forEach(function (_, i) { selectedSlicers.add(i); });

        buildDropdown(mainList, 'main');
        buildDropdown(compareList, 'compare');
        buildSlicers();
        setupEvents();

        // Show unmapped org warning if any
        var unmappedOrgs = (dataJson.meta && dataJson.meta.unmappedOrgs) ? dataJson.meta.unmappedOrgs : [];
        if (unmappedOrgs.length > 0) {
            dataStatus.textContent = '⚠️ ' + unmappedOrgs.length + ' orgs need mapping';
            dataStatus.classList.remove('loading');
            dataStatus.classList.add('warning');
            console.warn('=== UNMAPPED ORGANIZATIONS (' + unmappedOrgs.length + ') ===');
            unmappedOrgs.forEach(function (o) { console.warn('  ' + o); });
            console.warn('Add these to MapDeptGroup.xlsx then re-run update.bat');
        } else {
            dataStatus.textContent = '● Data Loaded';
            dataStatus.classList.remove('loading');
            dataStatus.classList.add('loaded');
        }

        var meta = dataJson.meta || {};
        console.log('Dashboard initialized: ' +
            dataJson.data.length + ' data points, ' +
            dataJson.years.length + ' years, ' +
            dataJson.parents.length + ' dept groups, ' +
            dataJson.children.length + ' orgs, ' +
            dataJson.slicerCats.length + ' SOBJ types.' +
            (meta.generatedAt ? ' Built: ' + meta.generatedAt : ''));

    } catch (e) {
        console.error('Init error:', e);
        dataStatus.textContent = '❌ ' + e.message;
        dataStatus.classList.remove('loading');
        dataStatus.classList.add('error');
    }
}


// ── Dropdown Builders ─────────────────────────────────────────────────────────
function extractHierarchy() {
    var hierarchy = {};
    for (var i = 0; i < dataJson.data.length; i++) {
        var r = dataJson.data[i];
        var pIdx = r[1];
        var cIdx = r[2];
        if (!hierarchy[pIdx]) hierarchy[pIdx] = new Set();
        hierarchy[pIdx].add(cIdx);
    }
    return hierarchy;
}

function buildDropdown(listEl, type) {
    var hierarchy = extractHierarchy();
    var sortedParents = Object.keys(hierarchy).map(Number).sort(function (a, b) {
        // Put EMPTY_MAP_LABEL at the end
        var na = dataJson.parents[a];
        var nb = dataJson.parents[b];
        if (na === EMPTY_MAP_LABEL) return 1;
        if (nb === EMPTY_MAP_LABEL) return -1;
        return na.localeCompare(nb);
    });

    var html = '';
    var allCb = type === 'compare' ? '<div class="dd-checkbox"></div>' : '';
    // "All Canada" top-level option
    html += '<div class="dd-item is-parent" data-type="all" data-id="-1" style="border-bottom: 1px solid var(--border-light); margin-bottom: 6px; padding-bottom: 12px;">' +
        allCb +
        '<span class="dd-icon">🇨🇦</span>' +
        '<span class="dd-text">All (Total Federal)</span>' +
        '</div>';

    for (var d = 0; d < sortedParents.length; d++) {
        var pIdx = sortedParents[d];
        var parentName = dataJson.parents[pIdx];
        var cSet = Array.from(hierarchy[pIdx]).sort(function (a, b) {
            return dataJson.children[a].localeCompare(dataJson.children[b]);
        });

        var isEmptyGroup = parentName === EMPTY_MAP_LABEL;
        var cb = type === 'compare' ? '<div class="dd-checkbox"></div>' : '';
        var icon = isEmptyGroup ? '⚠️' : '🏛️';
        var style = isEmptyGroup ? ' style="color: #f59e0b;"' : '';

        html += '<div class="dd-item is-parent" data-type="parent" data-id="' + pIdx + '"' + style + '>' +
            cb +
            '<span class="dd-icon">' + icon + '</span>' +
            '<span class="dd-text">' + parentName + '</span>' +
            '</div>';

        for (var m = 0; m < cSet.length; m++) {
            var cIdx = cSet[m];
            var childName = dataJson.children[cIdx];
            html += '<div class="dd-item is-child" data-type="child" data-id="' + cIdx + '">' +
                cb +
                '<span class="dd-text">' + childName + '</span>' +
                '</div>';
        }
    }

    listEl.innerHTML = html;
}

function buildSlicers() {
    var html = '';
    dataJson.slicerCats.forEach(function (cat, i) {
        var color = SLICER_COLORS[i % SLICER_COLORS.length];
        html += '<button class="slicer-btn active" data-id="' + i + '">' +
            '<span class="slicer-color-indicator" style="background-color: ' + color + '"></span>' +
            cat +
            '</button>';
    });
    slicerArea.innerHTML = html;
}

// ── Events ────────────────────────────────────────────────────────────────────
function setupEvents() {
    document.addEventListener('click', function (e) {
        if (!e.target.closest('#mainDropdown')) document.getElementById('mainDropdown').classList.remove('open');
        if (!e.target.closest('#compareDropdown')) document.getElementById('compareDropdown').classList.remove('open');
    });

    mainDropdownTrigger.addEventListener('click', function (e) {
        e.stopPropagation();
        document.getElementById('compareDropdown').classList.remove('open');
        document.getElementById('mainDropdown').classList.toggle('open');
    });

    compareDropdownTrigger.addEventListener('click', function (e) {
        e.stopPropagation();
        document.getElementById('mainDropdown').classList.remove('open');
        document.getElementById('compareDropdown').classList.toggle('open');
    });

    mainList.addEventListener('click', function (e) {
        var item = e.target.closest('.dd-item');
        if (!item) return;
        mainList.querySelectorAll('.dd-item').forEach(function (el) { el.classList.remove('selected'); });
        item.classList.add('selected');
        var type = item.getAttribute('data-type');
        var id = Number(item.getAttribute('data-id'));
        selectedMain = { type: type, id: id };
        var text = item.querySelector('.dd-text').textContent;
        mainDropdownTrigger.querySelector('.dropdown-label').textContent = text;
        document.getElementById('mainDropdown').classList.remove('open');
        updateChart();
    });

    compareList.addEventListener('click', function (e) {
        var item = e.target.closest('.dd-item');
        if (!item) return;
        var type = item.getAttribute('data-type');
        var id = Number(item.getAttribute('data-id'));
        var key = type + ':' + id;
        if (selectedCompare.has(key)) {
            selectedCompare.delete(key);
            item.classList.remove('selected');
        } else {
            selectedCompare.add(key);
            item.classList.add('selected');
        }
        var label = selectedCompare.size === 0 ? 'None selected' : selectedCompare.size + ' selected';
        compareDropdownTrigger.querySelector('.dropdown-label').textContent = label;
        updateChart();
    });

    compareClearBtn.addEventListener('click', function () {
        selectedCompare.clear();
        compareList.querySelectorAll('.dd-item').forEach(function (el) { el.classList.remove('selected'); });
        compareDropdownTrigger.querySelector('.dropdown-label').textContent = 'None selected';
        updateChart();
    });

    mainSearch.addEventListener('input', function (e) { filterList(e.target.value.toLowerCase(), mainList); });
    compareSearch.addEventListener('input', function (e) { filterList(e.target.value.toLowerCase(), compareList); });

    slicerArea.addEventListener('click', function (e) {
        var btn = e.target.closest('.slicer-btn');
        if (!btn) return;
        var id = Number(btn.getAttribute('data-id'));
        if (selectedSlicers.has(id)) {
            if (selectedSlicers.size === 1) return; // always keep at least one
            selectedSlicers.delete(id);
            btn.classList.remove('active');
        } else {
            selectedSlicers.add(id);
            btn.classList.add('active');
        }
        updateChart();
    });

    combineToggle.addEventListener('change', function (e) {
        isCombineOn = e.target.checked;
        updateChart();
    });
}

function filterList(term, listEl) {
    listEl.querySelectorAll('.dd-item').forEach(function (item) {
        var text = item.querySelector('.dd-text').textContent.toLowerCase();
        item.style.display = text.includes(term) ? 'flex' : 'none';
    });
}

// ── Chart Logic ───────────────────────────────────────────────────────────────
function formatValue(val) {
    if (val >= 1e12) return '$' + (val / 1e12).toFixed(1) + 'T';
    if (val >= 1e9) return '$' + (val / 1e9).toFixed(1) + 'B';
    if (val >= 1e6) return '$' + (val / 1e6).toFixed(1) + 'M';
    if (val >= 1e3) return '$' + (val / 1e3).toFixed(1) + 'K';
    return '$' + val;
}

function getSeriesData(selection) {
    var type = selection.type;
    var id = selection.id;
    var result = {};

    for (var i = 0; i < dataJson.data.length; i++) {
        var r = dataJson.data[i];
        var yIdx = r[0], pIdx = r[1], cIdx = r[2], sIdx = r[3], amt = r[4];

        // Filter by selection
        if (type === 'parent' && pIdx !== id) continue;
        if (type === 'child' && cIdx !== id) continue;
        // type === 'all' → include everything

        // Filter by active slicers
        if (!selectedSlicers.has(sIdx)) continue;

        if (!result[yIdx]) result[yIdx] = { total: 0, bySlicer: {} };
        result[yIdx].total += amt;
        if (!result[yIdx].bySlicer[sIdx]) result[yIdx].bySlicer[sIdx] = 0;
        result[yIdx].bySlicer[sIdx] += amt;
    }

    var sortedYears = Object.keys(result).map(Number).sort(function (a, b) {
        return dataJson.years[a] - dataJson.years[b];
    });

    return sortedYears.map(function (yIdx) {
        return {
            year: dataJson.years[yIdx],
            total: result[yIdx].total,
            bySlicer: result[yIdx].bySlicer
        };
    });
}

function getName(selection) {
    if (selection.type === 'all') return 'All (Total Federal)';
    if (selection.type === 'parent') return dataJson.parents[selection.id];
    return dataJson.children[selection.id];
}

function updateChart() {
    if (!selectedMain) {
        chartWrapper.classList.remove('active');
        emptyState.classList.remove('hidden');
        return;
    }

    chartWrapper.classList.add('active');
    emptyState.classList.add('hidden');

    var datasets = [];
    var mainSeries = getSeriesData(selectedMain);
    var mainName = getName(selectedMain);

    // X-axis labels: sorted fiscal year start integers
    var labels = dataJson.years.slice().sort(function (a, b) { return a - b; });

    chartTitle.textContent = 'Canada — ' + mainName + ' Expenses';
    updateSummaryCards(mainSeries, selectedMain);

    var scales = {};

    if (!isCombineOn) {
        // Stacked bars, one per SOBJ category
        Array.from(selectedSlicers).forEach(function (sIdx) {
            var catName = dataJson.slicerCats[sIdx];
            var color = SLICER_COLORS[sIdx % SLICER_COLORS.length];
            var dataPoints = labels.map(function (yr) {
                var found = mainSeries.find(function (s) { return s.year === yr; });
                return (found && found.bySlicer[sIdx]) ? found.bySlicer[sIdx] : 0;
            });
            datasets.push({
                type: 'bar',
                label: catName,
                data: dataPoints,
                backgroundColor: color,
                borderColor: 'transparent',
                yAxisID: 'y',
                stack: 'main'
            });
        });
    } else {
        // Single combined bar
        var dataPoints = labels.map(function (yr) {
            var found = mainSeries.find(function (s) { return s.year === yr; });
            return found ? found.total : 0;
        });
        datasets.push({
            type: 'bar',
            label: mainName + ' (Total)',
            data: dataPoints,
            backgroundColor: 'rgba(59, 130, 246, 0.5)',
            borderColor: '#3b82f6',
            borderWidth: 1,
            yAxisID: 'y'
        });
    }

    // Comparison lines
    if (selectedCompare.size > 0) {
        var colorIdx = 0;
        selectedCompare.forEach(function (compKey) {
            var parts = compKey.split(':');
            var cType = parts[0];
            var cId = Number(parts[1]);
            var cSer = getSeriesData({ type: cType, id: cId });
            var cName = getName({ type: cType, id: cId });
            var cPoints = labels.map(function (yr) {
                var found = cSer.find(function (s) { return s.year === yr; });
                return found ? found.total : 0;
            });
            datasets.push({
                type: 'line',
                label: cName + ' (Compare)',
                data: cPoints,
                borderColor: COMPARE_COLORS[colorIdx % COMPARE_COLORS.length],
                backgroundColor: 'transparent',
                borderWidth: 3,
                tension: 0.3,
                pointRadius: 4,
                yAxisID: 'y1'
            });
            colorIdx++;
        });
    }

    var gridColor = isLightMode ? 'rgba(0,0,0,0.06)' : 'rgba(255,255,255,0.04)';
    var textColor = isLightMode ? '#475569' : '#8b95b0';
    var legendColor = isLightMode ? '#0f172a' : '#f0f4fc';

    scales.y = {
        type: 'linear',
        position: 'left',
        title: { display: true, text: 'Amount (Main)', color: textColor },
        ticks: { color: textColor, callback: function (v) { return formatValue(v); } },
        grid: { color: gridColor },
        stacked: !isCombineOn
    };

    scales.x = {
        ticks: { color: textColor },
        grid: { color: gridColor },
        stacked: !isCombineOn
    };

    if (selectedCompare.size > 0) {
        scales.y1 = {
            type: 'linear',
            position: 'right',
            title: { display: true, text: 'Amount (Compare)', color: textColor },
            ticks: { color: textColor, callback: function (v) { return formatValue(v); } },
            grid: { drawOnChartArea: false }
        };
    }

    updateBreakdownTable(selectedMain, labels);

    if (mainChart) mainChart.destroy();
    var ctx = document.getElementById('mainChart').getContext('2d');
    mainChart = new Chart(ctx, {
        data: { labels: labels, datasets: datasets },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            interaction: { mode: 'index', intersect: false },
            plugins: {
                legend: { 
                    position: 'bottom',
                    labels: { color: legendColor } 
                },
                tooltip: {
                    callbacks: {
                        label: function (ctx) {
                            return ctx.dataset.label + ': ' + formatValue(ctx.parsed.y);
                        }
                    }
                }
            },
            scales: scales
        }
    });
}

// ── Breakdown Table ────────────────────────────────────────────────────────────
function updateBreakdownTable(selection, years) {
    var container = document.getElementById('breakdownContainer');
    var thead = document.getElementById('breakdownHeader');
    var tbody = document.getElementById('breakdownBody');
    var title = document.getElementById('breakdownTitle');

    if (!selection || years.length === 0) {
        container.classList.remove('active');
        return;
    }

    // Get the last 5 years
    var last5Years = years.slice(-5);
    var mostRecentYear = last5Years[last5Years.length - 1];

    var itemType = selection.type;
    var childrenKeys = [];
    var getNameFn;
    
    var hierarchy = extractHierarchy();

    if (itemType === 'all') {
        title.textContent = 'Top 10 Department Groups by Most Recent Spend';
        // children are all parents
        childrenKeys = dataJson.parents.map(function(_, i) { return i; });
        getNameFn = function(id) { return dataJson.parents[id]; };
    } else if (itemType === 'parent') {
        title.textContent = 'Top 10 Organizations by Most Recent Spend';
        // children are the children of this parent
        childrenKeys = hierarchy[selection.id] ? Array.from(hierarchy[selection.id]) : [];
        getNameFn = function(id) { return dataJson.children[id]; };
    } else if (itemType === 'child') {
        title.textContent = 'Top 10 Expense Types (SOBJ) by Most Recent Spend';
        childrenKeys = dataJson.slicerCats.map(function(_, i) { return i; });
        getNameFn = function(id) { return dataJson.slicerCats[id]; };
    }

    if (childrenKeys.length === 0) {
        container.classList.remove('active');
        return;
    }

    var itemsData = [];

    childrenKeys.forEach(function(childId) {
        var seriesData;
        if (itemType === 'all') {
            seriesData = getSeriesData({ type: 'parent', id: childId });
        } else if (itemType === 'parent') {
            seriesData = getSeriesData({ type: 'child', id: childId });
        } else {
            // For child, we need to extract the SOBJ data
            // We use the existing selected main child series, and grab bySlicer
            var childSeries = getSeriesData({ type: 'child', id: selection.id });
            seriesData = childSeries.map(function(s) {
                return {
                    year: s.year,
                    total: s.bySlicer[childId] || 0
                };
            });
        }

        var yearVals = {};
        seriesData.forEach(function(s) {
            yearVals[s.year] = s.total;
        });

        var mostRecentVal = yearVals[mostRecentYear] || 0;
        
        itemsData.push({
            id: childId,
            name: getNameFn(childId),
            yearVals: yearVals,
            mostRecentVal: mostRecentVal
        });
    });

    // Sort by most recent value desc
    itemsData.sort(function(a, b) {
        return b.mostRecentVal - a.mostRecentVal;
    });

    // Take top 10
    var top10 = itemsData.slice(0, 10);

    // Build header
    var headerHtml = '<th>Item</th>';
    last5Years.forEach(function(yr) {
        var yrStr = 'FY ' + yr + '-' + String(yr + 1).slice(-2);
        headerHtml += '<th class="right-align">' + yrStr + '</th>';
    });
    thead.innerHTML = headerHtml;

    // Build body
    var bodyHtml = '';
    top10.forEach(function(item, idx) {
        // Exclude completely zero rows
        var hasNonZero = last5Years.some(function(yr) { return (item.yearVals[yr] || 0) > 0; });
        if (!hasNonZero) return;
        
        bodyHtml += '<tr>';
        bodyHtml += '<td><strong>' + (idx + 1) + '.</strong> ' + item.name + '</td>';
        last5Years.forEach(function(yr) {
            var val = item.yearVals[yr] || 0;
            bodyHtml += '<td class="right-align">' + formatValue(val) + '</td>';
        });
        bodyHtml += '</tr>';
    });
    tbody.innerHTML = bodyHtml;

    container.classList.add('active');
}

// ── Summary Cards ─────────────────────────────────────────────────────────────
function updateSummaryCards(mainSeries, selection) {
    if (!mainSeries || mainSeries.length === 0) {
        document.getElementById('valLatestAmt').textContent = '—';
        document.getElementById('valLatestYear').textContent = '—';
        document.getElementById('val10yrGrowth').textContent = '—';
        document.getElementById('valAvgGrowth').textContent = '—';
        document.getElementById('valShare').textContent = '—';
        return;
    }

    mainSeries.sort(function (a, b) { return a.year - b.year; });

    var latest = mainSeries[mainSeries.length - 1];
    var latestAmt = latest.total;
    var latestYear = latest.year;

    // Card 1: Latest year
    document.getElementById('valLatestAmt').textContent = formatValue(latestAmt);
    document.getElementById('valLatestYear').textContent = 'FY ' + latestYear + '-' + String(latestYear + 1).slice(-2);

    // Card 2: 10-year growth
    var tenYearAgo = mainSeries.find(function (s) { return s.year === latestYear - 10; });
    if (tenYearAgo && tenYearAgo.total > 0) {
        var growth10 = ((latestAmt - tenYearAgo.total) / tenYearAgo.total) * 100;
        var el = document.getElementById('val10yrGrowth');
        el.textContent = (growth10 >= 0 ? '+' : '') + growth10.toFixed(1) + '%';
        el.style.color = growth10 >= 0 ? '#10b981' : '#f43f5e';
    } else {
        document.getElementById('val10yrGrowth').textContent = 'N/A';
        document.getElementById('val10yrGrowth').style.color = '';
    }

    // Card 3: CAGR
    var earliest = mainSeries[0];
    var yrs = latestYear - earliest.year;
    if (yrs > 0 && earliest.total > 0 && latestAmt > 0) {
        var cagr = (Math.pow(latestAmt / earliest.total, 1 / yrs) - 1) * 100;
        var el2 = document.getElementById('valAvgGrowth');
        el2.textContent = (cagr >= 0 ? '+' : '') + cagr.toFixed(1) + '%';
        el2.style.color = cagr >= 0 ? '#10b981' : '#f43f5e';
    } else {
        document.getElementById('valAvgGrowth').textContent = 'N/A';
        document.getElementById('valAvgGrowth').style.color = '';
    }

    // Card 4: % of Total Federal
    if (selection.type === 'all') {
        document.getElementById('valShare').textContent = '100%';
        document.getElementById('valShareYear').textContent = 'FY ' + latestYear;
    } else {
        var allSeries = getSeriesData({ type: 'all', id: -1 });
        var allLatest = allSeries.find(function (s) { return s.year === latestYear; });
        if (allLatest && allLatest.total > 0) {
            var share = (latestAmt / allLatest.total) * 100;
            document.getElementById('valShare').textContent = share.toFixed(1) + '%';
            document.getElementById('valShareYear').textContent = 'FY ' + latestYear;
        } else {
            document.getElementById('valShare').textContent = 'N/A';
        }
    }
}

// ── Start ─────────────────────────────────────────────────────────────────────
init();
